# Generated by Django 5.1.7 on 2025-03-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
