# Generated by Django 5.1.7 on 2025-03-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_visitorcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitorCount',
        ),
    ]
