# Generated by Django 5.1.7 on 2025-03-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_visitorcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image', models.ImageField(upload_to='blog_images/')),
                ('content', models.TextField()),
                ('sec1_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sec1_content', models.TextField(blank=True, null=True)),
                ('sec1_lang', models.CharField(blank=True, max_length=100, null=True)),
                ('sec1_lang_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec1_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('sec2_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sec2_content', models.TextField(blank=True, null=True)),
                ('sec2_lang', models.CharField(blank=True, max_length=100, null=True)),
                ('sec2_lang_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec2_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('sec3_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sec3_content', models.TextField(blank=True, null=True)),
                ('sec3_lang', models.CharField(blank=True, max_length=100, null=True)),
                ('sec3_lang_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec3_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('sec4_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sec4_content', models.TextField(blank=True, null=True)),
                ('sec4_lang', models.CharField(blank=True, max_length=100, null=True)),
                ('sec4_lang_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec4_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('sec5_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sec5_content', models.TextField(blank=True, null=True)),
                ('sec5_lang', models.CharField(blank=True, max_length=100, null=True)),
                ('sec5_lang_title', models.CharField(blank=True, max_length=100, null=True)),
                ('sec5_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('link1_text', models.CharField(blank=True, max_length=200, null=True)),
                ('link1_url', models.URLField(blank=True, null=True)),
                ('link2_text', models.CharField(blank=True, max_length=200, null=True)),
                ('link2_url', models.URLField(blank=True, null=True)),
                ('link3_text', models.CharField(blank=True, max_length=200, null=True)),
                ('link3_url', models.URLField(blank=True, null=True)),
                ('conclusion_title', models.CharField(blank=True, max_length=255, null=True)),
                ('conclusion_content', models.TextField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
