# Generated by Django 5.1.7 on 2025-04-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='sec1_lang_title',
            field=models.CharField(blank=True, max_length=32767, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec2_lang_title',
            field=models.CharField(blank=True, max_length=32767, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec3_lang_title',
            field=models.CharField(blank=True, max_length=32767, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec4_lang_title',
            field=models.CharField(blank=True, max_length=32767, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec5_lang_title',
            field=models.CharField(blank=True, max_length=32767, null=True),
        ),
    ]
