# Generated by Django 5.1.7 on 2025-04-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogposts_sec1_lang_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='sec1_lang',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec1_lang_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec2_lang',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec2_lang_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec3_lang',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec3_lang_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec4_lang',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec4_lang_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec5_lang',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec5_lang_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
