# Generated by Django 5.1.7 on 2025-04-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
