# Generated by Django 5.1.7 on 2025-04-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogposts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='linkconclusion_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='linkconclusion_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
