# Generated by Django 5.1.7 on 2025-04-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogposts_linkconclusion_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='linkconclusion_url',
            field=models.CharField(blank=True, null=True),
        ),
    ]
