# Generated by Django 5.1.7 on 2025-04-03 02:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blogposts_linkconclusion_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='linkconclusion_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='main_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='blog_media'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec1_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blog_media'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec2_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blog_media'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec3_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blog_media'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec4_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blog_media'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='sec5_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blog_media'),
        ),
    ]
