# Generated by Django 5.1.7 on 2025-04-03 02:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blogposts_linkconclusion_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blog_media'),
        ),
    ]
