# Generated by Django 5.1.7 on 2025-04-09 08:23

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_visitorcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('image_video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blog_media')),
                ('tech_stack', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('preview_url', models.URLField()),
                ('price', models.PositiveIntegerField(help_text='Price in INR paise (e.g., ₹499 → 49900)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
