# Generated by Django 5.1.7 on 2025-04-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_templateproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateProduct',
            new_name='TemplateProducts',
        ),
    ]
