# Generated by Django 5.1.7 on 2025-04-10 04:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_templateproduct_templateproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateproducts',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='templateproducts',
            name='image_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Product_media'),
        ),
    ]
