# Generated by Django 5.1.7 on 2025-04-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_templateproducts_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('razorpay_signature', models.CharField(max_length=255)),
                ('amount_paid', models.PositiveIntegerField(help_text='Amount in INR paise')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.templateproducts')),
            ],
        ),
    ]
