# Generated by Django 5.1.7 on 2025-04-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_templatepurchase_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in INR paise (e.g., ₹499.99 → 49999)', max_digits=12),
        ),
    ]
